# Generated by Django 5.0 on 2026-05-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulb_1', models.BooleanField(default=False)),
                ('bulb_2', models.BooleanField(default=False)),
                ('bulb_3', models.BooleanField(default=False)),
                ('bulb_4', models.BooleanField(default=False)),
                ('bulb_5', models.BooleanField(default=False)),
                ('bulb_6', models.BooleanField(default=False)),
                ('door_1', models.IntegerField(default=0)),
                ('door_2', models.IntegerField(default=0)),
                ('door_3', models.IntegerField(default=0)),
                ('door_4', models.IntegerField(default=0)),
                ('door_5', models.IntegerField(default=0)),
                ('door_6', models.IntegerField(default=0)),
                ('fan', models.BooleanField(default=False)),
                ('water_pump', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('gas_level', models.IntegerField()),
                ('fire_detected', models.BooleanField(default=False)),
                ('moisture_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
