# Generated by Django 5.0 on 2026-05-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecontrol',
            name='door_6',
        ),
    ]
